# Site settings
title: 小桥流水丿溪
email: 476490767@qq.com
description: > # this means to ignore newlines until "baseurl:"
  这是我的个人博客，使用Github Pages和Jekyll搭建 —— 唐泽雄
baseurl: "/sysutangzxBlog/" 
url: "http://cody1991.github.io/"
github_username:  cody1991
paginate: 2
paginate_path: "page:num"
